### ISSUE TITLE
Colorpedia

### ISSUE THREAD

**Issue by coderchai** [joowani/colorpedia#3]
just installed colorpedia using pip...
I cant seem to run this .. I am getting the following error message 

Traceback (most recent call last):
  File "/Users/user/anaconda3/bin/color", line 5, in <module>
    from colorpedia.cli import entry_point
  File "/Users/user/anaconda3/lib/python3.6/site-packages/colorpedia/__init__.py", line 1, in <module>
    from colorpedia.color import Color
  File "/Users/user/anaconda3/lib/python3.6/site-packages/colorpedia/color.py", line 1, in <module>
    from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'

Please help

**Comment by joowani** [comment]
Hi @coderchai,

I'll release a fix soon. Thanks for the bug report.

**Comment by joowani** [comment]
Hi again @coderchai,

I just released 1.2.0 with the fix. Please run `pip install colorpedia --upgrade` to upgrade. Feel free to reopen if you still have issues. Thanks!
